# Generated by Django 5.1.4 on 2026-06-23 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True, verbose_name='slug')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('telefone', models.CharField(blank=True, max_length=40, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('rua', models.CharField(blank=True, max_length=200, verbose_name='rua')),
                ('bairro', models.CharField(blank=True, max_length=120, verbose_name='bairro')),
                ('cidade', models.CharField(blank=True, max_length=120, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('mensagem', models.TextField(blank=True, verbose_name='mensagem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='recebido em')),
            ],
            options={
                'verbose_name': 'contato',
                'verbose_name_plural': 'contatos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='imagem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='loja.categoria', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['id'],
            },
        ),
    ]
