# Generated by Django 5.2.15 on 2026-06-23 10:17

import loja.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="produtos/",
                validators=[loja.validators.validar_imagem_produto],
                verbose_name="imagem",
            ),
        ),
    ]
